### ISSUE TITLE
How integrate this plugin with a Quasar app?

### ISSUE THREAD

**Issue by IvanWala** [OneSignal/onesignal-vue#10]
I want to know how integrate this plugin with a quasar app.

Especially this part

```
new Vue({
  render: h => h(App),
  beforeMount() {
    this.$OneSignal.init({ appId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' });
  }
}).$mount('#app')
```

Thanks a lot for the plugin..

**Comment by rgomezp** [comment]
Howdy Ivan,
Unfortunately, I'm not too familiar with Quasar. Were you able to resolve it by any chance? If so, please describe what you did to hopefully help others in the future facing similar issues.

Thanks in advance for your question and your help

**Comment by IvanWala** [comment]
Thanks I try Version 3 in a soon future,

**Comment by zvekov** [comment]
> I want to know how integrate this plugin with a quasar app.
> 
> Especially this part
> 
> ```
> new Vue({
>   render: h => h(App),
>   beforeMount() {
>     this.$OneSignal.init({ appId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' });
>   }
> }).$mount('#app')
> ```
> 
> Thanks a lot for the plugin..


I use {useOneSignal} (composition api + Nuxt 3)

```
import {onMounted} from 'vue'
import {useOneSignal} from '@onesignal/onesignal-vue3'
onMounted(async () => {
  await useOneSignal().init({appId: import.meta.env.VITE_ONESIGNAL_APP_ID})
})
```

**Comment by kamasuPaul** [comment]
Does this plugin work when used in a capacitor application? I am building a mobile app using **quasar**(capacitor mode). Just wondering if this plugin will be able to work when used in the context of  a capacitor mobile app?

**Comment by emawby** [comment]
@kamasuPaul I am not sure that is not something I believe we have tested. Typically capacitor mobile apps use our [Cordova SDK](https://github.com/OneSignal/OneSignal-Cordova-SDK)
