### ISSUE TITLE
Is plugin compliant with vue3 ?

### ISSUE THREAD

**Issue by this1-it** [OneSignal/onesignal-vue#15]
I see that dependencies are with vue2, but I give a try with vue3

plugin initialization is different, I'm doing:

```
import { createApp } from 'vue'
const app = createApp(App)
import OneSignalVue from 'onesignal-vue'
app.use(OneSignalVue)
```

then I got this exception, do you have any clue ?
Uncaught TypeError: Cannot set properties of undefined (setting '$OneSignal')

**Comment by jkasten2** [comment]
@this1-it Thanks for reporting, this plugin only supports Vue2 currently. We will be looking into adding Vue3 support in the future.

**Comment by this1-it** [comment]
I've already done the porting, plugin is loaded but I was not able to test yet 
because I do not have a valid key

Instead of 
`
export default OneSignalVuePlugin;`

`
I changed the export default,  I think you can handle both vue2 / vue3 

```
export default {
    install: (app: any, options: any) => {
        app.config.globalProperties.$OneSignal = OneSignalVue as IOneSignal;
    }
}
```
