### ISSUE TITLE
2.0.0 Release now in Beta!

### ISSUE THREAD

**Issue by rgomezp** [OneSignal/onesignal-vue#31]
🚧 Beta release. Please test thoroughly prior to production use. 🚧

In this major version beta release for the OneSignal SDK, we are making a significant shift from a device-centered model to a user-centered model. A user-centered model allows for more powerful omni-channel integrations within the OneSignal platform.

See the [migration guide](https://github.com/OneSignal/onesignal-vue/blob/user-model/v1/MigrationGuide.md) to get started.

We are looking for feedback. Please leave any questions or comments in the thread below.

Thank you

**Comment by jkasten2** [comment]
2.0.0 is now out of beta and has been released! See the full release notes:
https://github.com/OneSignal/onesignal-vue/releases/tag/2.0.0

This means no breaking changes will be made in 2.0.0. If you find a bug or have a feature require please create a new issue.
