### ISSUE TITLE
`OneSignal.init` function signature is incorrect

### ISSUE THREAD

**Issue by iAmWillShepherd** [OneSignal/onesignal-vue#6]
The `init` function signature incorrectly states `options` is optional.

```ts
init(options?: any): Promise<void>;
```

Given the `appId` is required to initialize the plugin, `options` cannot be optional. A more correct type signature for this function is:

```ts
init(options: any): Promise<void>;
```

Even with this correction, there is still the problem that I get no completions for the options object because it's typed as `any`. We should define a type for this object because the current one allows you to pass silly stuff like `init(false)`.

**Comment by rgomezp** [comment]
Fixed in code, need to update README
